# TUGAS
## Pengenalan Array dengan Numpy

Kelompok
1. Ameilia Indana Saputri
2. Andika Prasetya
3. Muhammad Daffa Sudarso
4. Nasya Oktafia Ramadhan


In [1]:
import numpy as np

# Membuat matriks 2x3 dengan tipe data int64
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks
print("Matriks arr:")
print(arr)

# Mencetak bentuk matriks
print("Bentuk arr:", arr.shape)

# Mencetak tipe data matriks
print("Tipe data arr:", arr.dtype)

Matriks arr:
[[1 2 3]
 [5 6 7]]
Bentuk arr: (2, 3)
Tipe data arr: int64


Logika Program : Mengimpor library NumPy dengan alias np. program ini akan menyediakan fungsi-fungsi oleh NumPy dengan mengetikkan np.nama_fungsi.
Membuat array 2x3 dengan fungsi np.array. Fungsi ini menerima sebuah list yang berisi list sebagai argumen pertama, dan tipe data yang diinginkan sebagai argumen kedua. Dalam hal ini, user akan membuat array yang berisi dua baris dan tiga kolom, dengan setiap elemen memiliki tipe data int64 (bilangan bulat 64-bit).
Mencetak array yang telah dibuat dengan fungsi print. Fungsi ini menampilkan nilai dari objek yang diberikan ke layar. Dalam hal ini, user mencetak array arr yang berisi [[1, 2, 3], [5, 6, 7]].
Mencetak bentuk array dengan atribut shape. Atribut ini mengembalikan sebuah tuple yang berisi jumlah baris dan kolom dari array. Selanjutnya akan mencetak (2, 3) yang menunjukkan bahwa array arr memiliki dua baris dan tiga kolom.
Mencetak tipe data array dengan atribut dtype. Atribut ini mengembalikan tipe data dari elemen-elemen dalam array. Dalam hal ini, juga akan mencetak int64 yang menunjukkan bahwa array arr memiliki elemen-elemen yang berupa bilangan bulat 64-bit.

In [2]:
import numpy as np

# Membuat matriks 2x3 dengan tipe data int64 dan nilai elemen acak
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# Mencetak matriks arr_rdm
print("Matriks arr_rdm:")
print(arr_rdm)

# Mencetak bentuk matriks arr_rdm
print("Bentuk arr_rdm:", arr_rdm.shape)

# Mencetak tipe data matriks arr_rdm
print("Tipe data arr_rdm:", arr_rdm.dtype)

Matriks arr_rdm:
[[13  5 79]
 [ 3 92  1]]
Bentuk arr_rdm: (2, 3)
Tipe data arr_rdm: int64


Logika Program : import numpy as np, untuk mengimport library NumPy memberikan alias np. selanjutanya arr_rdm ini akan membuat matriks dengan ukuran 2x3 yang berisi bilangan bulat acak antara 0 dan 100 (0-99). tipe data elemen matriks di atur di int 64 bit. 

# Aritmatika Dasar dengan Numpy

In [9]:
import numpy as np

# Matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Matriks arr_rdm (dengan elemen-elemen acak)
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# Operasi penjumlahan arr dan arr_rdm
addition_result = arr + arr_rdm

# Operasi pengurangan arr dan arr_rdm
subtraction_result = arr - arr_rdm

# Operasi perpangkatan dua arr_rdm
power_of_two_result = arr_rdm ** 2

# Operasi perkalian elemen arr dan arr_rdm
elementwise_multiplication_result = arr * arr_rdm

# Transpose matriks arr_rdm
transposed_arr_rdm = arr_rdm.T

# Operasi perkalian matriks arr dan arr_rdm (dot product)
matrix_multiplication_result = np.dot(arr, arr_rdm.T)  # Perbaikan di sini

# Mencetak hasil operasi
print("Hasil penjumlahan arr dan arr_rdm:")
print(addition_result)

print("Hasil pengurangan arr dan arr_rdm:")
print(subtraction_result)

print("Hasil perpangkatan dua arr_rdm:")
print(power_of_two_result)

print("Hasil perkalian elemen arr dan arr_rdm:")
print(elementwise_multiplication_result)

print("Transpose matriks arr_rdm:")
print(transposed_arr_rdm)

print("Hasil perkalian matriks arr dan arr_rdm (dot product):")
print(matrix_multiplication_result)

Hasil penjumlahan arr dan arr_rdm:
[[49 68 77]
 [51 60 86]]
Hasil pengurangan arr dan arr_rdm:
[[-47 -64 -71]
 [-41 -48 -72]]
Hasil perpangkatan dua arr_rdm:
[[2304 4356 5476]
 [2116 2916 6241]]
Hasil perkalian elemen arr dan arr_rdm:
[[ 48 132 222]
 [230 324 553]]
Transpose matriks arr_rdm:
[[48 46]
 [66 54]
 [74 79]]
Hasil perkalian matriks arr dan arr_rdm (dot product):
[[ 402  391]
 [1154 1107]]


Logika Program :

In [ ]:
Program di atas menggunakan library NumPy untuk melakukan berbagai operasi pada dua matriks, yaitu arr dan arr_rdm. Berikut adalah logika programnya:

Mengimpor library NumPy dengan alias np.
Membuat matriks arr dengan data yang telah ditentukan. Matriks arr memiliki dua baris dan tiga kolom dengan tipe data int64.
Membuat matriks arr_rdm dengan elemen-elemen acak. Matriks arr_rdm juga memiliki dua baris dan tiga kolom dengan tipe data int64.
Melakukan operasi penjumlahan antara matriks arr dan arr_rdm dengan menggunakan operator +. Hasilnya disimpan dalam variabel addition_result.
Melakukan operasi pengurangan antara matriks arr dan arr_rdm dengan menggunakan operator -. Hasilnya disimpan dalam variabel subtraction_result.
Melakukan operasi perpangkatan dua pada matriks arr_rdm dengan menggunakan operator **. Hasilnya disimpan dalam variabel power_of_two_result.
Melakukan operasi perkalian elemen antara matriks arr dan arr_rdm dengan menggunakan operator *. Hasilnya disimpan dalam variabel elementwise_multiplication_result.
Melakukan transpose pada matriks arr_rdm dengan menggunakan atribut .T. Hasil transpose disimpan dalam variabel transposed_arr_rdm.
Melakukan operasi perkalian matriks antara arr dan transpose dari arr_rdm menggunakan np.dot(). Hasilnya disimpan dalam variabel matrix_multiplication_result.
Mencetak hasil dari setiap operasi, termasuk penjumlahan, pengurangan, perpangkatan dua, perkalian elemen, transpose matriks arr_rdm, 
dan perkalian matriks dengan arr_rdm (dot product).

Program ini membantu Anda memahami bagaimana melakukan berbagai operasi matriks menggunakan NumPy, termasuk operasi elemen-wise, transpose, dan perkalian matriks.

In [5]:
import numpy as np

# Matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Menghitung nilai rata-rata seluruh matriks arr
mean_arr = np.mean(arr)

# Menghitung nilai rata-rata per baris matriks arr
mean_per_row = np.mean(arr, axis=1)

# Menghitung total nilai seluruh elemen matriks arr
total_sum = np.sum(arr)

# Menghitung nilai maksimum per kolom matriks arr
max_per_column = np.max(arr, axis=0)

# Mencetak hasil
print("Nilai rata-rata seluruh matriks arr:", mean_arr)
print("Nilai rata-rata per baris matriks arr:", mean_per_row)
print("Total nilai seluruh elemen matriks arr:", total_sum)
print("Nilai maksimum per kolom matriks arr:", max_per_column)


Nilai rata-rata seluruh matriks arr: 4.0
Nilai rata-rata per baris matriks arr: [2. 6.]
Total nilai seluruh elemen matriks arr: 24
Nilai maksimum per kolom matriks arr: [5 6 7]


Logika Program :

In [ ]:
Program di bawah ini menggunakan NumPy untuk melakukan operasi statistik pada matriks arr. Berikut adalah logika programnya:

Mengimpor library NumPy dengan alias np.
Membuat matriks arr dengan data yang diberikan. Matriks ini memiliki dua baris dan tiga kolom dengan tipe data int64.
Menghitung nilai rata-rata seluruh elemen dalam matriks arr menggunakan np.mean(arr). Hasilnya disimpan dalam variabel mean_arr.
Menghitung nilai rata-rata per baris matriks arr menggunakan np.mean(arr, axis=1). 
Ini menghasilkan rata-rata dari setiap baris matriks, dan hasilnya disimpan dalam variabel mean_per_row.
Menghitung total nilai dari seluruh elemen dalam matriks arr menggunakan np.sum(arr). Hasilnya disimpan dalam variabel total_sum.
Menghitung nilai maksimum per kolom matriks arr menggunakan np.max(arr, axis=0). 
Ini menghasilkan nilai maksimum dari setiap kolom matriks, dan hasilnya disimpan dalam variabel max_per_column.
Mencetak hasil perhitungan, termasuk nilai rata-rata seluruh matriks arr, nilai rata-rata per baris matriks arr, total nilai seluruh elemen matriks arr, 
dan nilai maksimum per kolom matriks arr.

Jadi, program ini digunakan untuk melakukan berbagai operasi statistik pada matriks NumPy, 
seperti menghitung rata-rata, total, dan nilai maksimum baik untuk seluruh matriks maupun per baris atau per kolom.

# Fitur pada Numpy

In [6]:
import numpy as np

# Membuat array arrg dengan nilai range 1-20
arrg = np.arange(1, 21)

# Mencetak array arrg
print("Array arrg:", arrg)

# Mencetak nilai arrg pada index 5
print("Nilai arrg index 5:", arrg[5])

# Mencetak nilai arrg untuk 3 elemen dari belakang
print("3 elemen dari belakang:", arrg[-3:])

# Mencetak nilai arrg dari indeks 3 sampai 6 (indeks 3, 4, 5, dan 6)
print("Nilai arrg dari indeks 3 sampai 6:", arrg[3:7])


Array arrg: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nilai arrg index 5: 6
3 elemen dari belakang: [18 19 20]
Nilai arrg dari indeks 3 sampai 6: [4 5 6 7]


Logika Program : 

In [ ]:
Program ini menggunakan library NumPy untuk membuat, mengakses, dan mencetak informasi dari sebuah array. Berikut adalah penjelasan logika dari program tersebut:

import numpy as np: Ini mengimpor library NumPy dan memberinya alias 'np' agar kita dapat mengakses fungsi-fungsi NumPy menggunakan 'np'.
arrg = np.arange(1, 21): Baris ini membuat array arrg yang berisi nilai dari 1 hingga 20. 
Fungsi np.arange(start, stop) digunakan untuk membuat array dengan nilai berurutan dari start (inklusif) hingga stop (eksklusif).

print("Array arrg:", arrg): Ini mencetak seluruh array arrg ke layar.
print("Nilai arrg index 5:", arrg[5]): Ini mencetak nilai yang terdapat pada index 5 dari array arrg. Ingatlah bahwa indeks dimulai dari 0, 
jadi nilai ini adalah elemen keenam dari array.
print("3 elemen dari belakang:", arrg[-3:]): Ini mencetak 3 elemen terakhir dari array arrg 
menggunakan indeks negatif. -1 adalah elemen terakhir, -2 adalah elemen kedua dari belakang, dan seterusnya.
print("Nilai arrg dari indeks 3 sampai 6:", arrg[3:7]): Ini mencetak nilai dalam array arrg mulai dari indeks 3 hingga sebelum indeks 7 (indeks 3, 4, 5, dan 6). 
Range ini dijelaskan dengan notasi arrg[start:stop], dimana elemen dengan indeks start akan disertakan, tetapi elemen dengan indeks stop akan dikecualikan.

Dengan demikian, program ini menggunakan NumPy untuk membuat, mengakses, dan mencetak informasi dari array arrg.

In [7]:
import numpy as np

# Matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks arr
print("Matriks arr:")
print(arr)

# Slicing matriks arr untuk menghasilkan output pertama
sliced_arr1 = arr[:, 1:]

# Mencetak hasil slicing pertama
print("Sliced arr (output pertama):")
print(sliced_arr1)

# Slicing matriks arr untuk menghasilkan output kedua
sliced_arr2 = arr[:, 2:]

# Mencetak hasil slicing kedua
print("Sliced arr (output kedua):")
print(sliced_arr2)


Matriks arr:
[[1 2 3]
 [5 6 7]]
Sliced arr (output pertama):
[[2 3]
 [6 7]]
Sliced arr (output kedua):
[[3]
 [7]]


Logika Program :

In [ ]:
Program di bawah ini menggunakan NumPy untuk memanipulasi matriks dan melakukan operasi slicing. Berikut adalah logika programnya:

Mengimpor library NumPy dengan alias np. Membuat matriks arr dengan data yang diberikan. Matriks ini memiliki dua baris dan tiga kolom dengan tipe data int64.
Mencetak matriks arr untuk menampilkan isi matriksnya. Ini mencetak seluruh matriks arr.

Melakukan slicing pada matriks arr untuk menghasilkan "output pertama" (sliced_arr1). 
Slicing dilakukan dengan mengambil semua baris (:) dan kolom kedua hingga terakhir (1:). 
Dengan demikian, hasil slicing pertama akan berisi kolom kedua dan ketiga dari matriks arr.

Mencetak hasil slicing pertama (sliced_arr1) untuk menampilkan output pertama. Ini akan mencetak kolom kedua dan ketiga dari matriks arr.
Melakukan slicing pada matriks arr untuk menghasilkan "output kedua" (sliced_arr2). 
Slicing dilakukan dengan mengambil semua baris (:) dan kolom ketiga hingga terakhir (2:). Dengan demikian, hasil slicing kedua akan berisi kolom ketiga dari matriks arr.
Mencetak hasil slicing kedua (sliced_arr2) untuk menampilkan output kedua. Ini akan mencetak kolom ketiga dari matriks arr.

Jadi, program ini mencetak matriks awal arr, kemudian melakukan dua operasi slicing berbeda untuk menghasilkan output pertama dan output kedua, 
dan akhirnya mencetak hasil dari kedua operasi slicing tersebut.

In [8]:
import numpy as np

# Membuat matriks 3x4 dengan tipe data int64 dan nilai elemen acak
mtx_rdm = np.random.randint(0, 100, size=(3, 4), dtype=np.int64)

# Mencetak bentuk matriks mtx_rdm
print("Bentuk mtx_rdm sebelum perubahan:", mtx_rdm.shape)

# Mengubah bentuk matriks mtx_rdm menjadi satu dimensi
mtx_rdm_1d = mtx_rdm.flatten()

# Mencetak bentuk matriks mtx_rdm setelah menjadi satu dimensi
print("Bentuk mtx_rdm setelah menjadi satu dimensi:", mtx_rdm_1d.shape)

# Mengubah bentuk matriks mtx_rdm menjadi 6x2
mtx_rdm_6x2 = mtx_rdm.reshape(6, 2)

# Mencetak bentuk matriks mtx_rdm setelah menjadi 6x2
print("Bentuk mtx_rdm setelah menjadi 6x2:", mtx_rdm_6x2.shape)


Bentuk mtx_rdm sebelum perubahan: (3, 4)
Bentuk mtx_rdm setelah menjadi satu dimensi: (12,)
Bentuk mtx_rdm setelah menjadi 6x2: (6, 2)


Logika Program :

In [ ]:
Program di atas menggunakan library NumPy untuk membuat, mengubah bentuk, dan mencetak informasi matriks. 
Berikut adalah penjelasan logika dari program tersebut:

import numpy as np: Seperti sebelumnya, ini mengimpor library NumPy dan memberinya alias 'np' agar kita dapat mengakses fungsi-fungsi NumPy menggunakan 'np'.
mtx_rdm = np.random.randint(0, 100, size=(3, 4), dtype=np.int64): 
Ini membuat matriks mtx_rdm dengan ukuran 3x4 (3 baris dan 4 kolom) yang berisi angka-angka acak antara 0 dan 99. Tipe data elemen-elemen matriks ini diatur ke int64.

print("Bentuk mtx_rdm sebelum perubahan:", mtx_rdm.shape): Ini mencetak bentuk (jumlah baris dan kolom) dari matriks mtx_rdm sebelum mengalami perubahan. 
shape adalah atribut matriks yang mengembalikan tupel berisi jumlah baris dan kolom.

mtx_rdm_1d = mtx_rdm.flatten(): Matriks mtx_rdm diubah menjadi satu dimensi menggunakan metode flatten(). Hasilnya disimpan dalam variabel mtx_rdm_1d.

print("Bentuk mtx_rdm setelah menjadi satu dimensi:", mtx_rdm_1d.shape): Ini mencetak bentuk dari matriks mtx_rdm_1d setelah diubah menjadi satu dimensi. 
Sekarang, mtx_rdm_1d adalah array satu dimensi.

mtx_rdm_6x2 = mtx_rdm.reshape(6, 2): Matriks mtx_rdm diubah menjadi matriks 6x2 menggunakan metode reshape(). 
Ini berarti matriks asli dengan 3 baris dan 4 kolom diubah menjadi matriks dengan 6 baris dan 2 kolom.

print("Bentuk mtx_rdm setelah menjadi 6x2:", mtx_rdm_6x2.shape): Ini mencetak bentuk dari matriks mtx_rdm_6x2 setelah mengalami perubahan bentuk. 
Sekarang, matriks ini memiliki 6 baris dan 2 kolom.

Dengan demikian, program ini membuat, mengubah bentuk, dan mencetak informasi dari matriks menggunakan NumPy.